"""update column

Revision ID: 33ce6a5cbe5b
Revises: fc446cb8e823
Create Date: 2020-10-27 13:48:41.215516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33ce6a5cbe5b'
down_revision = 'fc446cb8e823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('pitch_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('categories', sa.Column('category_title', sa.String(length=255), nullable=True))
    op.drop_column('categories', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('categories', 'category_title')
    op.drop_table('comments')
    # ### end Alembic commands ###
