"""add email column

Revision ID: 9edfbe885a7d
Revises: 9ae028a4e996
Create Date: 2020-10-26 15:25:35.138252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9edfbe885a7d'
down_revision = '9ae028a4e996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('description', sa.String(), nullable=True))
    op.create_index(op.f('ix_pitches_description'), 'pitches', ['description'], unique=False)
    op.create_foreign_key(None, 'pitches', 'categories', ['category_id'], ['id'])
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_index(op.f('ix_pitches_description'), table_name='pitches')
    op.drop_column('pitches', 'description')
    op.drop_column('pitches', 'category_id')
    # ### end Alembic commands ###
