"""add category

Revision ID: a651d29432c9
Revises: 33ce6a5cbe5b
Create Date: 2020-10-27 13:56:25.461905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a651d29432c9'
down_revision = '33ce6a5cbe5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_pitches_category'), 'pitches', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pitches_category'), table_name='pitches')
    op.drop_column('pitches', 'category')
    # ### end Alembic commands ###
