"""update pitch

Revision ID: bf4ea8f02a87
Revises: e4b278fdf077
Create Date: 2020-10-27 15:54:28.605118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf4ea8f02a87'
down_revision = 'e4b278fdf077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_pitches_category'), 'pitches', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pitches_category'), table_name='pitches')
    op.drop_column('pitches', 'category')
    # ### end Alembic commands ###
