"""update pitch

Revision ID: e4b278fdf077
Revises: a651d29432c9
Create Date: 2020-10-27 15:52:01.523303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b278fdf077'
down_revision = 'a651d29432c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('post', sa.Text(), nullable=False))
    op.alter_column('pitches', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pitches', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index('ix_pitches_category', table_name='pitches')
    op.drop_index('ix_pitches_description', table_name='pitches')
    op.drop_column('pitches', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_index('ix_pitches_description', 'pitches', ['description'], unique=False)
    op.create_index('ix_pitches_category', 'pitches', ['category'], unique=False)
    op.alter_column('pitches', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('pitches', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('pitches', 'post')
    # ### end Alembic commands ###
